### ISSUE TITLE
feature request: add a bracket or brackets automatically to completions

### ISSUE THREAD

**Issue by maxim-uvarov** [vincev/dply-rs#27]
Hi! It seems to me that it would be convenient to automatically add to completions:
- brackets if no arguments are expected (as in `glimpse()`) 
- or a single bracket if arguments are expected (as in `mutate(`). 

Please consider adding this feature.

**Comment by vincev** [comment]
Hi @maxim-uvarov this looks like a good improvement, I'll try to add it.
