### ISSUE TITLE
great work!

### ISSUE THREAD

**Issue by fdncred** [vincev/dply-rs#31]
Just passing on some love here. Great work on this tool! I'm really appreciating your approach to it. Dataframes can be difficult to deal with and you've hidden most of the complexity for users. I'd love to build your stuff into nushell if I could find an easy way to do it.

**Comment by vincev** [comment]
Hi @fdncred thank you for the kind words! nushell is super nice it inspired me to add reedline support to dply. For dply-rs I took inspiration from Hadley Wickham [dplyr](https://dplyr.tidyverse.org/), I find it very intuitive to use and can be extended by adding new functions.

Currently the crate exports `interpreter::eval` that evaluates a whole pipeline input and sends the output to standard output but I am not sure if that helps to integrate it in nushell.

**Comment by fdncred** [comment]
I'd like it to work like the nushell pipeline works. We have slightly different syntax though. I'll keep thinking about it. I mostly wanted to stop by and say Hi! and great job!
