### ISSUE TITLE
Implicit default sink for pipelines

### ISSUE THREAD

**Issue by not-my-profile** [vincev/dply-rs#43]
By sink I mean `show`, `glimpse`, `csv`, `json`, `parquet` and pipeline variables (which could become `into`, see #42).

Every step of a pipeline that isn't followed by a sink is just dead code ... completely useless since the results will be discarded.

This is particularly unintuitive since dply currently doesn't print any warning or error about such dead code. It also makes the REPL a bit cumbersome since you have to append `| show()` to pretty much every single query and every time you want to append a filter to the pipeline, you press <kbd>ArrowUp</kbd> and then have to move the cursor before the `| show()` to insert the new filter.

I think it would be better if dply would detect that there's no sink and just append a default sink, which would be `show()` for the REPL but could perhaps be configured on the command-line so that you could execute the same query with different output formats without having to edit the query file e.g:

```
$ dply example.query --to json
$ dply example.query --to csv
```

**Comment by vincev** [comment]
I prefer explicit rather than implicit if a dply script writes to json or csv it should be visible in the script.
