### ISSUE TITLE
Why is the datafusion dependency a git dependency?

### ISSUE THREAD

**Issue by not-my-profile** [vincev/dply-rs#44]
This was changed in 96dd5ba4f17ebcb68402f479dd0d64db48a39578 without explaining why. If there's a reason why dply currently has to depend on that particular commit of datafusion that should probably explained in a comment in `Cargo.toml`.

**Comment by vincev** [comment]
I would agree with you if this was a release branch but master contains changes toward a release and in this case is depending on DataFusion master as they are adding features moving toward 28.
