### ISSUE TITLE
Enhance: Auto backtick "invalid" column names

### ISSUE THREAD

**Issue by tikkanz** [vincev/dply-rs#51]
The column completion really improves ergonomics!

Would it be possible when inserting a chosen a column name that would require backticks to be valid (for example contains a `-`), to automatically surround the column name with backticks?

**Comment by vincev** [comment]
Hi @tikkanz this should be easy and useful to have, I'll add it.

**Comment by vincev** [comment]
thank you @tikkanz I have added backtick completions here #54.
