### ISSUE TITLE
compile for older glibc?

### ISSUE THREAD

**Issue by colindaven** [vincev/dply-rs#55]
Interesting package, thanks. Could you please consider making this package compile and run on Ubuntu 20.04, eg with an older glibc?

```
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

```

This would make it much easier to deploy ad hoc in a container etc (I know I can use cargo but thats more top heavy).

Thanks,
Colin

```
./dply 
./dply: /usr/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by ./dply)
./dply: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./dply)
./dply: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./dply)
./dply: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./dply)

```

**Comment by vincev** [comment]
Hi @colindaven I added  `dply-0.2.0-x86_64-ubuntu-20.04.zip` LTS to the release action, you can find the binary in [the release page](https://github.com/vincev/dply-rs/releases/tag/v0.2.0), let me know how it goes.

**Comment by colindaven** [comment]
Thanks for the quick response, I got a chance to test and it works perfectly.
Colin
